version: '3'
services:
    apache2:
        build:
          dockerfile: Dockerfile
          context: .
        tty: true
        ports:
          - '8080:80'
    # mariadb:
        # restart: always
        # build:
          # dockerfile: Dockerfile
          # context: ./controller
        # ports:
          # - '5000:80'