version: '3'
services:
    apache2:
        build:
          dockerfile: Dockerfile
          context: .
        tty: true
        ports:
          - '8080:80'
    mysql:
        image: mariadb:10.3
        restart: always
        container_name: mariadb
        volumes:
          - ./db:/docker-entrypoint-initdb.d
        environment:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - "3300:3306"
